Feature/autoplay focus change
Serraniel/AniwatchPlus pull request #174
Opened 2021-02-06 22:11 UTC by kaffem

PoC for #173

2021-02-07 17:46 UTC, Serraniel requested changes
The rest looks fine to me. I like the decision to make the resume optional, too.

2021-02-07 17:46 UTC, Serraniel commented on src/javascript/enhancements/anilyr.ts
> +let onVisible: boolean;
Maybe would rename it to indicate it's a Boolean. `onSomething` mostly is used for events or listeners.

```suggestion
let restartPlayerOnVisible: boolean;
```

2021-02-08 05:05 UTC, kaffem commented on src/javascript/enhancements/anilyr.ts
> +let onVisible: boolean;
I agree, instead of 'restart' I used 'resume' since it fits the overall functionality better.

2021-02-08 17:29 UTC, Serraniel approved these changes

2021-02-08 17:30 UTC, merged