Feature/#19 notifications tab title
Serraniel/AniwatchPlus pull request #31
Opened 2020-08-04 16:34 UTC by kaffem

2020-08-05 09:49 UTC, Serraniel requested changes
I think the code how to get the notification count can be improved a bit more regarding its stability in case the user is logged out or there are no notifications.

2020-08-05 09:49 UTC, Serraniel commented on enhancements/notifications.js
> +    let notificationText = menuDropdowns.innerText.split("  ")[3];
Is 3 the correct index here? I just executed this via console and it wasn´t working correctly I think:
![image](https://user-images.githubusercontent.com/8461282/89397194-d5d1d000-d70f-11ea-804b-f4ca40b9c65d.png)

There probably also has to be a check if user is logged in and if there even is a notification I think. 
You may try getting it via regular expression: 
```js
menuDropdowns.querySelector('li a[href="notification"]')?.innerText?.match('\\d+')[0] ?? '' 
```

2020-08-05 09:49 UTC, Serraniel commented on enhancements/notifications.js
> +    document.title = __notificationCount + document.title;
We should also insert a space after the number (at least the code I put in the other comment is without space). Also only add the space if there are notifications to insert.

2020-08-05 13:54 UTC, kaffem commented on enhancements/notifications.js
> +    let notificationText = menuDropdowns.innerText.split("  ")[3];
> 
> 
> Is 3 the correct index here? I just executed this via console and it wasn´t working correctly I think:
> ![image](https://user-images.githubusercontent.com/8461282/89397194-d5d1d000-d70f-11ea-804b-f4ca40b9c65d.png)
Yeah the 3 is the correct index here, your split is missing another space.
![chrome_8SQg6ZZOCH](https://user-images.githubusercontent.com/29717789/89420569-2eff2b00-d733-11ea-95e1-8735ac78c4eb.png)

2020-08-05 13:57 UTC, kaffem commented on enhancements/notifications.js
> +    document.title = __notificationCount + document.title;
Right now there is a space added after the number in line 16; however I'll take a look into retrieving the notificationCount via regex since its not always working on pathnames like /watch2gether

2020-08-20 15:52 UTC, kaffem commented on enhancements/notifications.js
> +    let notificationText = menuDropdowns.innerText.split("  ")[3];
> There probably also has to be a check if user is logged in and if there even is a notification I think.

9fe2668c3afec7a4b100cffc9ae722d1baa13fe7 adds checks for logged in + notifications

2020-09-11 16:03 UTC, Serraniel approved these changes

2020-09-13 22:37 UTC, kaffem reviewed
Considering the things mentioned, I'd suggest we either put this feature on hold until #42 gets resolved, or we use the old solution with the pathnameChange instead of the pushState event, or we use the new solution on /home and whenever the user opens his notifications (/notification) to update the NotificationCount. With this assigned to a variable we then just use the variable to insert the NotificationCount into the title on all the other pathnames.

2020-09-13 22:37 UTC, kaffem commented on src/javascript/enhancements/notifications.js
> +        updateNotificationsInTitle();
Getting the NotificationCount on every pushState event increases the chance of it failing. With this solution it fails for every item of the Community and Anime dropdownmenus. With the old solution it failed when inserting the Count into the title for the stats, jobs, seasonal, airing, random, profile, watchlist and notifications. 10 vs 8 pathnames where it doesn't work.
Furthermore with this solution we run into problems on the profile pathname: 
![chrome_yyDTOAsutx](https://user-images.githubusercontent.com/29717789/93030124-fe0ef180-f620-11ea-99b3-151a7ed6a99b.png)
We are adding the NotificationCount to the old count whenever we switch from one tab under profile to another; this did not happen with the old solution.

This seems to be related to #42 tho, if you enable Low-end mobile and check the pathnames after visting /home first, you'll see the notification count appear for a while and then disappear once the site is fully shown. With the new solution its definitely because of #42; we are trying to access the menu while the page isn't fully loaded.

2020-09-13 22:37 UTC, kaffem commented on src/javascript/utils/aniwatchCore.js
> +export function runAfterPathnameChange(func, pattern = '.*') {
We should rename this, if we keep using the pushState event.

2020-09-13 22:37 UTC, kaffem commented on src/javascript/utils/aniwatchCore.js
> +export function isLoggedIn() {
I don't quite understand, why you moved this from helpers to core.

2020-09-16 19:32 UTC, Serraniel commented on src/javascript/utils/aniwatchCore.js
> +export function runAfterPathnameChange(func, pattern = '.*') {
What would you suggest? Maybe location change? I think each pushstate also always could be a location change maybe?

2020-09-16 19:33 UTC, Serraniel commented on src/javascript/utils/aniwatchCore.js
> +export function isLoggedIn() {
The current helper file more was intended for JS helpers, not website helpers. But I agree that core already also is very mixed up between extension core and aniwatch core. This should be optimized in the feature I think.

2020-09-16 19:36 UTC, Serraniel commented on src/javascript/enhancements/notifications.js
> +        updateNotificationsInTitle();
Do you remember how exactly you produced that bug with the number written in the title multiple times? I haven´t seen that yet. 

But something else I noticed was the fact, the title seems to be updated by aniwatch after the blue loading bar on the top disappears. This should be investigated as a new opportunity to decide when we update the title and also would fix the current issue, that we just guess a random number to wait until location change before we update the title, which doesn´t always works as the following gif shows:
![2020-09-16_21-32-11-463](https://user-images.githubusercontent.com/8461282/93383974-b7a9d480-f864-11ea-9ec9-8b560256357b.gif)

2020-09-17 22:30 UTC, kaffem commented on src/javascript/enhancements/notifications.js
> +        updateNotificationsInTitle();
Yeah thats what I meant. Looks like we should not only wait for the popState but also for onload once their preloader is fixed, or wait for the loading bar to disappear(?)

2020-09-17 22:32 UTC, kaffem commented on src/javascript/utils/aniwatchCore.js
> +export function runAfterPathnameChange(func, pattern = '.*') {
```suggestion
export function runAfterLocationChange(func, pattern = '.*') {
```

would be fine imo

2020-10-25 09:57 UTC, Serraniel commented on src/javascript/enhancements/notifications.js
> +        updateNotificationsInTitle();
I introduced another observer, which will execute after the blue loading bar in the top disappears. This error seems not to appear any more with that specific change.

2020-10-25 09:58 UTC, Serraniel commented on src/javascript/utils/aniwatchCore.js
> +export function runAfterPathnameChange(func, pattern = '.*') {
Renamed this with commit a840f644b723cb885232f4184698db2a27bc5f7d

2020-10-25 10:00 UTC, Serraniel commented on src/javascript/enhancements/notifications.js
> +        updateNotificationsInTitle();
- [ ] There still is the problem, that some pages have a different loading method where the menu isn´t available directly in the DOM.

2020-10-25 10:29 UTC, Serraniel commented on src/javascript/enhancements/notifications.js
> +        updateNotificationsInTitle();
I was able to fix this. We started our scripts after the preloader disappeared. We now also wait for the `document.readyState`  to be `"complete"` so we can ensure *everything* is loaded correctly, as the preloader disappears to early on some pages.

2020-10-25 10:32 UTC, Serraniel approved these changes

2020-10-25 10:32 UTC, Serraniel commented
We can ignore the failing Travis builds for now, they are some kind of "global" issue in the project.

2020-10-25 10:33 UTC, Serraniel commented
@kaffem if there are no objections by you I think we could merge this now.

2020-10-25 21:02 UTC, Serraniel commented on src/javascript/utils/aniwatchCore.js
> +        if (preLoader.style.display === "none" && document.readyState === 'complete') {
This also fixes #42 .

2020-10-28 00:02 UTC, kaffem reviewed
Yes. That's it. Works good!

2020-10-28 05:46 UTC, merged